# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f6581b754c5cbfcfb4b6dd6a8f012ea25837e581a30204fc6173a8ec478d84e628b11f3952d9657c590c97eaaf90f2bf2d97828b427700839ac8674d845a8c

test:
  secret_key_base: 1714e64f66d8a6f5928077f9c2c2fa8ce13f4fd4adaf15b816cc2f533d3d4a957a68984f408688f996b5ed0dbac4f03bc12b41e00d20133ffb6e4e9703da939a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
